### ISSUE TITLE
Feature suggestion: Predefined Subpatterns

### ISSUE THREAD

**Issue by Haringat** [florianingerl/com.florianingerl.util.regex#1]
I would like to predefine a set of subpatterns for later reference in recursion. The PCRE syntax for the definition is
```regex
(?(DEFINE)(?<name>pattern))
```
Those patterns can later be referred to with e.g.
```regex
(?&name)
```
The benefit of this is that you can better structure your regular expressions and don't need the patterns to have matched anything before you reference them.

**Comment by florianingerl** [comment]
Great suggestion! Do you want to contribute?

**Comment by florianingerl** [comment]
The feature is now implemented in Version 1.0.3 (also available for download from Maven Central).

The syntax differs a bit from the PCRE syntax.  You refer to a subpattern with (?name) instead of (?&name).

**Comment by Haringat** [comment]
Thanks a lot.
