### ISSUE TITLE
Suggestion: group name with underscore

### ISSUE THREAD

**Issue by hexosse** [florianingerl/com.florianingerl.util.regex#3]
Thanks for this library, that's exactly what I was looking for.

Could it be possible to have group name containing underscore?
That's will make syntax clearer on big expression.

ex: `(?'group_name')` instead of `(?'groupName')`

**Comment by florianingerl** [comment]
The latest commit makes underscores in group names possible.
When version 1.1.6 is ready for download on maven (hopefully tomorrow), you will be able to use that feature.
