### ISSUE TITLE
com.florianingerl.util.regex.PatternSyntaxException: Unknown inline modifier near index 13 \{(?:[^{}]|(?R))*\}

### ISSUE THREAD

**Issue by thegeekybaniya** [florianingerl/com.florianingerl.util.regex#4]
Got the above error for the following code

` String regex = "\\{(?:[^{}]|(?R))*\\}";

        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(pBody);
        if (matcher.find()) {
            System.out.println(matcher.group(1));

        }`

**Comment by florianingerl** [comment]
Be aware that the syntax (?R) or (?0) as in Perl is not supported by this library, only (?n) where n is greater than 0 or (?'groupName') is supported. 
So solve your problem by 
String regex = "(\{(?:[^{}]|(?1))*\})";

**Comment by thegeekybaniya** [comment]
Still not working

**Comment by florianingerl** [comment]
Sorry, the escapes before { and } were somehow removed in my answer. So the regex
String regex = "(\\{(?:[^{}]|(?1))*\\})";
should do the job.

**Comment by thegeekybaniya** [comment]
Worked like a charm thanks!
