### ISSUE TITLE
match expression in named group

### ISSUE THREAD

**Issue by Vintic** [florianingerl/com.florianingerl.util.regex#6]
How to match the expression in a capture group?

There are multiple syntaxes for this feature: \g<name> \g'name' (?&name) (?P>name).
But it don't working. "Illegal/unsupported escape sequence near index".
Example: `(?&message)zxc(?<message>\d{3})`
should match: 123zxc456

It works using "numeric subroutine":  `(?1)zxc(\d{3})`

Thanks for this library!

**Comment by florianingerl** [comment]
The following code prints "Everything worked like a charm!" to the console.





	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Pattern p = Pattern.compile("(?'name')zxc(?<name>\\d{3})");
		if(p.matcher("123zxc456").matches() ) {
			System.out.println("Everything worked like a charm!");
		}
	}
