### ISSUE TITLE
'Illegal repetition' error

### ISSUE THREAD

**Issue by kplich** [florianingerl/com.florianingerl.util.regex#7]
`public static final Pattern OBJECT_CONTENT = Pattern.compile("(\\w+\\s*:\\s*(\\w+,?|\\{\\s*(?1)+\\s*,?}|\\[\\s*({\\s*(?1)+\\s*},?\\s*)*\\s*],?)\\s*),?", Pattern.DOTALL);`

The following pattern does not compile and causes a
```
PatternSyntaxException: Illegal repetition near index 40
(\w+\s*:\s*(\w+,?|\{\s*(?2)+\s*,?}|\[\s*({\s*(?2)+\s*},?\s*)*\s*],?)\s*),?
                                        ^
```

I developed the regex using https://regex101.com (PCRE flavor) and it compiles correctly.

(direct link to mentioned expression and test string: https://regex101.com/r/WNzCJ1/1)

I tried to look under the hood to see what's causing the error, but couldn't make much of it and the message itself isn't particularly useful.

Thanks in advance for any help.

**Comment by florianingerl** [comment]
The curly brace at index 40 is not escaped.  The syntax, that this regex engine uses, is the same that java.util.regex uses. Following Java code would also produce a Pattern.Syntax.Exception:
[Pattern.compile("({hello})");](url)

**Comment by kplich** [comment]
Thank you for your help.

>
